import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./_components/1layout/Header";
import Footer from "./_components/1layout/Footer";
import { Providers } from "./provider";
import ToastifyContainer from "./_components/general/ToastifyContainer.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// This layout is used for all pages in the app
// It is used to wrap all pages in the app
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ToastifyContainer />
          {/* Header */}
          <div className="mt-3 mx-4 xl:mx-44">
            <Header />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
